//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTMDreport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GTMDReportEntities : DbContext
    {
        public GTMDReportEntities()
            : base("name=GTMDReportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Classification> Classifications { get; set; }
        public virtual DbSet<IndexIndustrie> IndexIndustries { get; set; }
        public virtual DbSet<IndustryCassification2> IndustryCassification2 { get; set; }
        public virtual DbSet<IndustrycCassification> IndustrycCassifications { get; set; }
        public virtual DbSet<NonPublicIndustrie> NonPublicIndustries { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
    }
}
